version: '3'
services:
  bitwarden:
    env_file: bitwarden.env
    image: mprasil/bitwarden
    restart: always
    container_name: bitwarden
    volumes: 
      - $HOST_BW_DATA_PATH:/data
      - $HOST_SSL_PATH:/ssl/
    ports: 
      - $HOST_PORT:80

  backup: 
    image: bruceforce/bw_backup
    container_name: bitwarden_backup
    restart: always
    volumes:
      - $HOST_BW_DATA_PATH:/data
    environment:
      CRON_TIME: "0 * * * *"

  certbot:
    image: certbot/certbot

      
      
    
