version: '3'
services:
  bitwarden:
    env_file: bitwarden.env
    image: mprasil/bitwarden
    restart: unless-stopped
    container_name: bitwarden
    environment:
      - DOMAIN=$DOMAIN
    volumes: 
      - $HOST_BW_DATA_DIR:/data

  backup: 
    image: bruceforce/bw_backup
    container_name: bitwarden_backup
    restart: unless-stopped
    volumes:
      - $HOST_BW_DATA_DIR:/data
    environment:
      CRON_TIME: "0 * * * *"


  backup_gcs:
    image: dkhroad/bw_backup
    container_name: bitwarden_backup_gcs
    restart: unless-stopped
    environment:
      - GS_AUTH2_REFRESH_TOKEN=$GS_AUTH2_REFRESH_TOKEN
      - PROJECT_ID=$PROJECT_ID

    volumes:
      - $HOST_BW_DATA_DIR:/data

  nginx:
    image: nginx:mainline-alpine
    container_name: bw_nginx
    #depends_on: 
    #  - certbot
    ports:
      - "$HOST_HTTP_PORT:80"
      - "$HOST_HTTPS_PORT:443"
    restart: unless-stopped
    volumes:
      - $NGINX_CONF_DIR:/etc/nginx/conf.d
      - $CERTBOT_DIR/conf:/etc/letsencrypt
      - $CERTBOT_DIR/www:/var/www/certbot
    command: "/bin/sh -c 'envsubst < /etc/nginx/conf.d/app.conf.tmpl > /etc/nginx/conf.d/app.conf && exec nginx -g \"daemon off;\" && \
              while :; do sleep 6h & wait $${i}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      - ESC=$$
      - SERVER_FQDN=$DOMAIN

  certbot:
    image: dkhroad/certbot
    container_name: bw_certbot
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - DOMAIN=$DOMAIN
      - STAGING=$STAGING
    volumes:
      - $CERTBOT_DIR/conf:/etc/letsencrypt
      - $CERTBOT_DIR/www:/var/www/certbot


      
      
    
