version: '3'
services:
  bitwarden:
    env_file: $BITWARDEN_ENV_FILE
    image: mprasil/bitwarden
    restart: always
    container_name: bitwarden
    volumes: 
      - $HOST_BW_DATA_PATH:/data
      - $HOST_SSL_PATH:/ssl/
    ports: 
      - $HOST_PORT:80

  backup: 
    image: bruceforce/bw_backup
    container_name: bitwarden_backup
    restart: always
    volumes:
      - $HOST_BW_DATA_PATH:/data
    environment:
      CRON_TIME: "0 * * * *"


  backup_gcs:
    env_file: bitwarden_backup_gcs.env
    image: dkhroad/bw_backup
    container_name: bitwarden_backup_gcs
    restart: always
    volumes:
      - $HOST_BW_DATA_PATH:/data


  # nginx:
  #   image: nginx:mainline-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     $NGNIX_DATA_PATH:/etc/nginx/conf.d

  certbot:
    image: certbot/certbot

      
      
    
